import os

def create_files(base_dir, files_dict):
    os.makedirs(base_dir, exist_ok=True)
    for filename, content in files_dict.items():
        filepath = os.path.join(base_dir, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content.strip() + '\n')
    print(f"Created {len(files_dict)} files in {base_dir}")

rl_dir = "docs/02-discovery/resource-logistics"
rl_files = {
    "README.md": "# Resource and Logistics Domain Knowledge Base\nThis directory contains the modular Discovery Knowledge Base for the Resource and Logistics domain.",
    "RESOURCE_LOGISTICS_DISCOVERY.md": "---\nid: DOC-DISC-RESOURCE_LOGISTICS\ntitle: RESOURCE & LOGISTICS DOMAIN DISCOVERY (EXECUTIVE)\nversion: 1.0\nstatus: Draft\nowner: Discovery\n---\n# Resource and Logistics Domain Discovery (Executive Narrative)\n\nThe Resource and Logistics Domain exists to execute approved humanitarian support plans by managing the physical and financial flow of assistance. It bridges the gap between a justified need (assessed by Case Management) and the actual delivery of material, services, or cash to the affected person.\n\nWhile Programme Management determines *what* to do and Case Management determines *who* needs it, Resource and Logistics determines *how* to source, transport, and distribute it. It handles procurement, supply chain, warehousing, cash transfers, vendor relationships, and final distribution.\n\nSuccessful outcomes of this domain include the safe, timely, and dignified delivery of aid, precise auditability of all resources from origin to beneficiary, and efficient management of operational supply chains. The domain balances critical tensions, such as the speed of emergency procurement versus the compliance requirements of anti-fraud separation of duties.\n\nFor authoritative business knowledge, concepts, rules, and events, refer to the modular artifacts within this Knowledge Base.",
    "01-domain-overview.md": "# Domain Overview: Resource and Logistics\n\n## Purpose\nTo physically and financially execute humanitarian interventions.\n\n## Mission\nEnsure that the right assistance reaches the right person at the right time, safely and efficiently, while maintaining an auditable, unbroken trail of resources from origin to beneficiary.\n\n## Scope\nThe domain encompasses procurement, warehousing, inventory management, transport, cash disbursement, vendor management, and last-mile distribution.\n\n## Responsibilities\n- Sourcing goods and services (Procurement)\n- Managing Vendors and Financial Service Providers (FSPs)\n- Warehousing and tracking inventory\n- Dispatching and transporting goods\n- Managing physical Distribution Points\n- Executing Cash-Based Interventions (CBIs)\n- Confirming fulfillment (delivery receipt)",
    "02-boundaries.md": "# Domain Boundaries: Resource and Logistics\n\n## Owns\n- Supply chain management.\n- Warehousing and inventory.\n- Procurement and vendor management.\n- Cash transfer execution.\n- Physical distribution operations.\n\n## Consumes\n- **From Case Management:** Execution triggers (approved Support Plans) indicating who needs what and where.\n- **From Programme Management:** Budgets and intervention catalogues (predictive demand for procurement).\n\n## Produces\n- **For Case Management:** Fulfillment status (confirmation that aid was delivered or failed).\n- **For Programme Management:** Spend rates, market feasibility reports, and stock alerts.\n\n## Explicitly Out of Scope\n- Assessing beneficiary vulnerability (Case Management).\n- Defining program eligibility rules and budgets (Programme Management).\n- Monitoring long-term beneficiary outcomes (Accountability & Evaluation).\n- Handling beneficiary grievances regarding aid quality (Accountability & Evaluation).",
    "03-concepts.md": "# Business Concepts\n\n- Warehouse\n- Stock / Inventory\n- Shipment / Consignment\n- Distribution Point\n- Financial Service Provider (FSP)\n- Vendor / Supplier\n- Procurement Request\n- Purchase Order\n- Waybill / Dispatch Note\n- Execution Trigger (Fulfillment Order)\n- Cash Transfer\n- In-kind Good\n- Service Voucher\n- Delivery Confirmation / Receipt\n- Market Capacity",
    "04-relationships.md": "# Business Relationships\n\n- A **Warehouse** stores **Inventory**.\n- A **Procurement Request** generates a **Purchase Order**.\n- A **Purchase Order** is fulfilled by a **Vendor**.\n- An **Execution Trigger** demands an **Intervention Offering**.\n- A **Shipment** transfers **Inventory** to a **Distribution Point**.\n- A **Distribution Point** facilitates **Delivery Confirmation**.\n- A **Financial Service Provider** executes a **Cash Transfer**.\n- **Inventory** fulfills an **Execution Trigger**.",
    "05-business-rules.md": "# Business Rules\n\n## Universal Rules\n- **Anti-Fraud Separation of Duties:** The individual who procures goods cannot be the same individual who receives them into stock; the individual who authorizes a distribution cannot physically hand out the goods.\n- Aid must be delivered in a manner that ensures the physical safety and dignity of the recipient.\n\n## Donor Rules\n- Procurement often requires minimum competitive bidding (e.g., at least 3 quotes).\n- Origin constraints (e.g., funds cannot be used to purchase goods from specific embargoed countries).\n\n## Organisation Rules\n- Financial thresholds dictating whether procurement can be localized or must be tendered internationally.\n\n## Operational Constraints\n- **Cold Chain:** Medical supplies require unbroken temperature-controlled logistics.\n- **Liquidity:** Cash distributions in remote areas are constrained by the physical cash liquidity of local agents.",
    "06-business-events.md": "# Business Events\n\n- **Procurement Initiated:** A need for stock is formally requested.\n- **Goods Received:** Items arrive at a warehouse and enter inventory.\n- **Stock Alert Triggered:** Inventory falls below minimum thresholds or nears expiration.\n- **Execution Trigger Received:** Case Management requests the delivery of an approved Support Plan.\n- **Dispatch Authorized:** Goods are assigned to a waybill and leave the warehouse.\n- **Goods in Transit:** Physical movement of material.\n- **Cash Transfer Instructed:** FSP is ordered to release funds to a beneficiary.\n- **Fulfillment Confirmed:** Cryptographic or physical signature verifying the beneficiary received the aid.\n- **Distribution Failed:** Aid could not be delivered (beneficiary absent, logistics breakdown, security incident).",
    "07-business-lifecycles.md": "# Business Lifecycles\n\nThe domain manages two distinct lifecycles:\n\n## 1. The Procurement Lifecycle (Upstream)\n1. **Needs Identification:** Recognizing a deficit against Programme demand.\n2. **Sourcing & Bidding:** Identifying vendors.\n3. **Purchase Order:** Legally committing to buy.\n4. **Receipt & Quality Control:** Accepting goods into the warehouse.\n5. **Inventory:** Goods sit in active stock.\n\n## 2. The Fulfillment Lifecycle (Downstream)\n1. **Execution Trigger Received:** Case Management hands off an approved plan.\n2. **Allocation:** Reserving specific stock or cash for the trigger.\n3. **Dispatch:** Moving the resource to the Distribution Point or FSP.\n4. **Distribution:** The physical or digital handover.\n5. **Delivery Confirmation:** Formal closure of the execution loop.",
    "08-decision-points.md": "# Significant Business Decisions\n\n## 1. Procurement Sourcing Decision\nDetermining whether to buy locally, regionally, or internationally.\n- **Required Information:** Market feasibility, cost, lead times, donor constraints.\n- **Responsible Business Role:** Procurement Officer / Logistics Manager.\n- **Justification:** Balance the speed of local procurement against the scale and cost-efficiency of international procurement.\n\n## 2. Dispatch Prioritisation Decision\nDetermining which execution triggers to fulfill first when available stock is lower than total demand.\n- **Required Information:** Inventory levels, Case Management vulnerability priorities.\n- **Responsible Business Role:** Logistics Coordinator.\n- **Justification:** Ensure life-saving interventions are fulfilled before resilience-building interventions during acute shortages.\n\n## 3. Vendor / FSP Selection Decision\nDetermining which commercial entity will provide goods or facilitate cash transfers.\n- **Required Information:** Bids, security vetting, past performance, geographic reach.\n- **Responsible Business Role:** Procurement Committee.\n- **Justification:** Mitigate fraud, ensure reliability, and comply with donor regulations.",
    "09-information-requirements.md": "# Information Requirements\n\nTo perform its business activities, the Resource and Logistics domain requires:\n- **Execution Triggers:** Who the person is, what they are approved for, and their location (consumed from Case Management).\n- **Inventory Visibility:** Real-time, accurate counts of stock across all warehouses and transit nodes.\n- **Vendor/Market Data:** Catalogues, pricing, lead times, and FSP network coverage.\n- **Security & Access Context:** Understanding whether a transport route or distribution point is physically safe to operate.",
    "10-open-questions.md": "# Open Questions\n\n- How is the physical security of a distribution point formally verified and continually reassessed before and during a dispatch?\n- How are partial fulfillments structurally handled (e.g., a beneficiary is approved for a full hygiene kit, but the warehouse only has soap)? Does Case Management or Logistics own the \"backorder\" state?\n- How does the domain manage cash liquidity crises in local markets when electronic transfers (mobile money) fail due to network outages?\n- How is the return of uncollected goods (reverse logistics) managed when beneficiaries fail to appear at a distribution point?",
    "11-evidence.md": "# Supporting Evidence\n\n*(Pending Discovery)*\nCurrently, the knowledge is drawn from cross-referencing standard supply chain operations in emergency response. Explicit evidentiary documents to be linked include:\n- Sphere Standards (Logistics and supply chain chapters).\n- WFP/UNHCR Cash-Based Intervention (CBI) guidelines.\n- INGO standard operating procedures for procurement and anti-fraud.",
    "12-domain-invariants.md": "# Domain Invariants\n\nEnduring truths that define Resource and Logistics:\n- **Separation of Assessment and Delivery:** The entity that decides someone is eligible for aid (Case Management) cannot be the entity that physically hands out the aid (Logistics).\n- **The Audit Trail:** Every single unit of material or cash must be mathematically traceable from procurement origin to beneficiary receipt.\n- **Execution Without Question:** Logistics does not second-guess the vulnerability assessment; if an Execution Trigger is validly signed by Case Management, Logistics fulfills it.",
    "13-business-language.md": "# Business Language\n\n## Preferred Terms\n- **Fulfillment:** The complete act of delivering the approved intervention.\n- **Execution Trigger:** The authoritative instruction from Case Management to deliver aid.\n- **Waybill:** The authoritative document tracking goods in transit.\n- **FSP:** Financial Service Provider (e.g., a mobile money operator or bank).\n\n## Synonyms\n- **Delivery:** Synonym for Fulfillment.\n- **Beneficiary List / Distribution List:** Older synonyms for a batch of Execution Triggers.\n\n## Ambiguous Terminology\n- **Distribution:** Can ambiguously refer to the allocation of budgets (Programme Management) or the physical handing out of goods (Logistics). In this domain, it strictly means physical handover.",
    "STATUS.md": "# Status\n\n`\nOverview: Complete\nBoundaries: Complete\nConcepts: Complete\nRelationships: Complete\nBusiness Rules: Complete\nEvents: Complete\nLifecycles: Complete\nDecision Points: Complete\nInformation Requirements: Complete\nOpen Questions: 4 identified\nEvidence: Pending Discovery\nDomain Invariants: Complete\nBusiness Language: Complete\nClient Validation: Pending\nOverall Discovery Maturity: READY FOR FREEZE\n`"
}

create_files(rl_dir, rl_files)
