import os

def create_files(base_dir, domain_name, files_dict):
    os.makedirs(base_dir, exist_ok=True)
    for filename, content in files_dict.items():
        filepath = os.path.join(base_dir, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content.strip() + '\n')
    print(f"Created {len(files_dict)} files in {base_dir}")

# Case Management
cm_dir = "docs/02-discovery/case-management"
cm_files = {
    "README.md": "# Case Management Domain Knowledge Base\nThis directory contains the modular Discovery Knowledge Base for the Case Management domain.",
    "CASE_MANAGEMENT_DISCOVERY.md": "---\nid: DOC-DISC-CASE_MANAGEMENT\ntitle: CASE MANAGEMENT DOMAIN DISCOVERY (EXECUTIVE)\nversion: 1.2\nstatus: Frozen\nowner: Discovery\n---\n# Case Management Domain Discovery (Executive Narrative)\n\nThe Case Management Domain exists to govern the individual and household lifecycle of humanitarian assistance. It solves the problem of understanding a specific person's or household's lived reality, identifying their vulnerabilities, determining their eligibility for assistance, and maintaining a continuous relationship with them over time.\n\nSuccessful outcomes of this domain include a verified understanding of an individual's context, justified recommendations that match verified needs to available resources, and a continuity of care that adapts as the individual's situation changes.\n\nThe domain operates a core cognitive lifecycle: acquiring evidence directly from individuals, forming an understanding of their vulnerabilities, verifying claims, reasoning to justify a support plan, and continuously reassessing. It balances critical business tensions daily, such as the ethical pressure for rapid response versus the operational mandate for rigorous evidence verification.\n\nFor authoritative business knowledge, concepts, rules, and events, refer to the modular artifacts within this Knowledge Base.",
    "01-domain-overview.md": "# Domain Overview: Case Management\n\n## Purpose\nThe Case Management Domain exists to govern the individual and household lifecycle of humanitarian assistance. It solves the problem of understanding a specific person's or household's lived reality, identifying their vulnerabilities, determining their eligibility for assistance, and maintaining a continuous relationship with them over time.\n\n## Mission\nTo ensure an individual receives appropriate, timely support based on verified truth rather than assumption, and that their administrative engagement accurately reflects their real-world recovery progress.\n\n## Scope\nFocuses on the micro-level assessment, planning, and monitoring of individual cases. It interacts directly with affected populations to gather claims, consent, and context.\n\n## Responsibilities\n- Screening and Intake\n- Identity Resolution & Duplicate Investigation\n- Consent Management\n- Needs Assessment & Vulnerability Reassessment\n- Evidence Gathering & Documentation Validation\n- Household Composition Review\n- Safeguarding Review\n- Support Planning\n- Referral Coordination\n- Monitoring & Follow-up Planning\n- Case Note Maintenance\n- Case Closure & Exception Handling",
    "02-boundaries.md": "# Domain Boundaries: Case Management\n\n## Owns\n- Individual intake and assessment.\n- Support planning (matching needs to interventions).\n- Verification of individual claims.\n- Ongoing monitoring of the individual.\n\n## Consumes\n- **From Programme Management:** Eligibility rules, intervention catalogues, and operational budgets.\n- **From Resource & Logistics:** Fulfillment status indicating aid was delivered.\n\n## Produces\n- **For Resource & Logistics:** Triggered execution plans for fulfillment.\n\n## Dependencies\n- Dependent on Programme Management for rules and budgets.\n- Dependent on Resource & Logistics to physically deliver the aid.\n\n## Explicitly Out of Scope\n- Regional needs assessments and budgeting (Programme Management).\n- Procurement and financial disbursement (Resource & Logistics).\n- Long-term systemic impact evaluation and independent grievance handling (Accountability & Evaluation).\n- Deduplication across NGOs (Cross-Organisational Coordination).",
    "03-concepts.md": "# Business Concepts\n\n- Case\n- Support Plan\n- Vulnerability\n- Vulnerability Indicator\n- Risk\n- Priority\n- Safeguarding Concern\n- Need\n- Claim\n- Evidence\n- Observation\n- Identity\n- Household Composition\n- Eligibility\n- Consent\n- Assessment\n- Referral\n- Follow-up\n- Case Note\n- Service Episode\n- Decision Justification\n- Escalation\n- Duplicate Case\n- Community Validation\n- Engagement Stage\n- Human Development Stage\n- Household\n- Intervention Offering",
    "04-relationships.md": "# Business Relationships\n\n- An **Individual** participates in a **Household**.\n- A **Household** contains multiple **Individuals**.\n- A **Caregiver** represents a **Dependent Individual**.\n- A **Case Worker** manages a **Case**.\n- A **Case** tracks a person's **Engagement Stage** independent of their **Human Development Stage**.\n- A **Case** produces **Decisions**.\n- A **Need** belongs to a **Case**.\n- A **Claim** requires **Evidence**.\n- **Evidence** supports a **Decision**.\n- An **Observation** contributes to an **Assessment**.\n- A **Vulnerability** generates a **Need**.\n- A **Risk** influences a **Priority**.\n- **Consent** authorizes an **Activity**.\n- A **Decision** produces a **Decision Justification**.\n- A **Need** justifies a **Support Plan**.\n- A **Support Plan** includes an **Intervention**.\n- An **Intervention** addresses a **Need**.\n- A **Referral** transfers responsibility to a **Referral Partner**.",
    "05-business-rules.md": "# Business Rules\n\n## Universal Rules\n- Evidence must precede execution.\n- Consent must be obtained (unless overridden by the necessity exception for life/safety).\n\n## Regional Rules\n- The definition of a \"household\" and acceptable verification methods vary by cultural context.\n\n## Organisation-Specific Rules\n- Individual NGOs define internal approval chains and specific thresholds for case closure.\n\n## Programme Rules (Consumed)\n- Eligibility rules dictate whether a verified need can actually be supported by a given intervention.\n\n## Operational Constraints\n- Must preserve dignity and agency.\n- Must not override another Organisation's independent assessment.\n- Must maintain strict data privacy and consent tracking.",
    "06-business-events.md": "# Business Events\n\n- **Intake Initiated:** A person presents themselves or is identified.\n- **Consent Granted:** Beneficiary explicitly agrees to terms.\n- **Consent Withdrawn:** Beneficiary revokes previous agreement.\n- **Duplicate Identified:** A potential identity collision is flagged.\n- **Household Updated:** Composition changes (e.g., birth, separation).\n- **Claim Recorded:** A specific need or circumstance is stated.\n- **Evidence Verified:** A claim is independently confirmed.\n- **Evidence Invalidated:** Previously accepted proof is found fraudulent or expired.\n- **Evidence Expired:** Verification ages past policy threshold.\n- **Assessment Completed:** The holistic context of the individual is synthesised.\n- **Safeguarding Concern Raised:** A critical protection risk is identified.\n- **Risk Escalated:** A vulnerability reaches a critical threshold.\n- **Support Plan Proposed:** An intervention is recommended.\n- **Support Plan Approved:** A human authorizes the intervention.\n- **Execution Triggered:** The plan is passed to Resource & Logistics for fulfillment.\n- **Fulfillment Confirmed:** Notification received that aid was delivered.\n- **Support Suspended:** Interventions paused due to compliance, security, or eligibility loss.\n- **Referral Created:** A need is sent to a partner Organisation.\n- **Referral Accepted / Rejected:** Partner response received.\n- **Appeal Submitted:** Beneficiary contests a decision.\n- **Appeal Resolved:** Final determination made.\n- **Reassessment Triggered:** New information or time elapsed requires another assessment.\n- **Case Closed:** The active intervention cycle is formally ended.\n- **Case Reopened:** A closed case requires new intervention.",
    "07-business-lifecycles.md": "# Business Lifecycles\n\n## The Core Cognitive Lifecycle\nThe domain operates a non-linear, looping lifecycle for an individual case:\n1. **Screening and Intake**\n2. **Needs Assessment**\n3. **Support Planning**\n4. **Execution / Handoff** (Implementation via Resource & Logistics)\n5. **Monitoring**\n6. **Reassessment** (Loops back to Assessment or Planning based on changing context)\n7. **Case Closure**\n\n## Dual Lifecycles\nThere is a strict structural separation between a person's administrative status and their actual recovery:\n- **Engagement Stage Lifecycle:** Tracks the administrative participation in the system (e.g., Registered, Active, Suspended, Closed).\n- **Human Development Stage Lifecycle:** Tracks the individual's underlying progress toward resilience (e.g., Acute Crisis, Stabilized, Resilient).",
    "08-decision-points.md": "# Significant Business Decisions\n\n## 1. Eligibility Decision\nDetermining if an individual's verified needs meet the criteria for a specific intervention.\n- **Required Information:** Verified claims, field observations, vulnerability indicators.\n- **Responsible Business Role:** Case Worker (Recommendation) -> Approver (Final Decision).\n- **Justification:** Ensure resources are allocated fairly to those who meet programme criteria.\n\n## 2. Reassessment Decision\nDetermining if a case needs to be reopened or escalated based on new information.\n- **Required Information:** Fulfillment loops, new claims, changing context, follow-up observations.\n- **Responsible Business Role:** Case Worker.\n- **Justification:** Ensure continuity of care and adapt to changing ground realities.\n\n## 3. Referral Decision\nDetermining if a need should be transferred to an external Partner Organisation.\n- **Required Information:** Needs assessment identifying out-of-scope vulnerabilities, explicit beneficiary consent.\n- **Responsible Business Role:** Case Worker or Protection Officer.\n- **Justification:** Connect individuals with specialized care outside the current Organisation's mandate.\n\n## 4. Safeguarding Escalation Decision\nDetermining if immediate intervention is required to protect a vulnerable individual from harm.\n- **Required Information:** Direct observation, community reports, safeguarding flags.\n- **Responsible Business Role:** Protection Officer or Senior Case Worker.\n- **Justification:** Prevent immediate abuse, exploitation, or severe harm.",
    "09-information-requirements.md": "# Information Requirements\n\nTo perform its business activities, the Case Management domain requires:\n- **Identity & Context:** Who the person is, their household structure, and their environment.\n- **Claims:** What the person states they need or have experienced.\n- **Evidence/Observations:** Corroborating proof supporting or refuting claims.\n- **Operational Rules & Budgets:** The constraints and catalogues passed down from Programme Management.\n- **Fulfillment Status:** Confirmation from Resource & Logistics that aid was delivered.",
    "10-open-questions.md": "# Open Questions\n\n- How is the authority to approve a Support Plan operationally delegated during an acute crisis?\n- What are the exact informal criteria practitioners use to determine if an intervention \"worked\" prior to formal reassessment?\n- How are conflicting evidence sources reconciled in practice when community validation contradicts documentary proof?\n- How is uncertainty formally represented when an assessor suspects a vulnerability but lacks hard evidence?\n- How are duplicate households mathematically or operationally resolved when identified across distinct Organisations?\n- How are conflicting assessments managed when two Organisations evaluate the same individual differently?\n- How are informal community recommendations structurally validated within the formal approval chain?\n- How are referrals tracked across organisations when systems lack direct interoperability?\n- How is consent practically revoked and propagated once data has already been shared?\n- How are vulnerable minors represented when no Legal Guardian or Caregiver is present?\n- How are culturally sensitive cases (e.g., domestic abuse) managed without endangering the beneficiary?\n- How are safeguarding concerns rapidly escalated outside standard Programme rules?",
    "11-evidence.md": "# Supporting Evidence\n\n*(Pending Discovery)*\nCurrently, the knowledge is drawn from cross-referencing field observations and existing normative models (like the Humanitarian Business Reference Model), but explicit evidentiary documents (e.g., UNHCR guidelines, Sphere standards, ICRC manuals) will be catalogued here as they are formally introduced to justify specific rules.",
    "12-domain-invariants.md": "# Domain Invariants\n\nEnduring truths that define Case Management:\n- **The Threshold for Human Review:** Any decision whose error could materially affect a person's rights requires meaningful human review. High-consequence decisions cannot be fully automated.\n- **Evidence Precedes Execution:** A verified understanding of reality must exist before material resources are committed.\n- **Separation of Assessment from Delivery:** Assessing a need (Case Management) is structurally distinct from physically delivering the aid (Resource & Logistics).\n- **Dignity & Agency:** The beneficiary is an active agent, not a passive recipient; their consent and autonomy are fundamental constraints on all operations.",
    "13-business-language.md": "# Business Language\n\n## Preferred Terms\n- **Case:** The overarching container for a person's interaction with the system.\n- **Support Plan:** The authorized intervention strategy for a case.\n- **Claim:** An unverified assertion of need or identity.\n- **Evidence:** Independently corroborated proof.\n- **Case Worker:** The primary human role assessing the individual.\n\n## Synonyms\n- **Assessment:** Often used interchangeably with Screening or Intake in informal conversation.\n- **Beneficiary / Registrant / Affected Person:** Synonyms for the individual seeking or receiving aid depending on their stage in the lifecycle.\n\n## Ambiguous Terminology\n- **Needs Assessment:** Can refer to a macro-level Programme activity or a micro-level Case activity.\n- **Closure:** Can mean the end of a single intervention episode or the permanent exit of the beneficiary from the system.",
    "STATUS.md": "# Status\n\n`\nOverview: Complete\nBoundaries: Complete\nConcepts: Complete\nRelationships: Complete\nBusiness Rules: Complete\nEvents: Complete\nLifecycles: Complete\nDecision Points: Complete\nInformation Requirements: Complete\nOpen Questions: 12 identified\nEvidence: Pending Discovery\nDomain Invariants: Complete\nBusiness Language: Complete\nClient Validation: Pending\n`"
}

# Programme Management
pm_dir = "docs/02-discovery/programme-management"
pm_files = {
    "README.md": "# Programme Management Domain Knowledge Base\nThis directory contains the modular Discovery Knowledge Base for the Programme Management domain.",
    "PROGRAMME_MANAGEMENT_DISCOVERY.md": "---\nid: DOC-DISC-PROGRAMME_MANAGEMENT\ntitle: PROGRAMME MANAGEMENT DOMAIN DISCOVERY (EXECUTIVE)\nversion: 1.2\nstatus: Frozen\nowner: Discovery\n---\n# Programme Management Domain Discovery (Executive Narrative)\n\nThe Programme Management Domain exists to govern the macro-level coordination, resourcing, and strategic boundaries of humanitarian assistance. It solves the problem of allocating finite resources against systemic vulnerabilities by defining what assistance will be provided, to whom it is available, and under what conditions. It bridges the gap between institutional funding mandates and frontline case management operations.\n\nCase Management cannot perform these responsibilities because it operates at the altitude of the individual; a case worker cannot assess global community needs or independently decide how to spend an organisation's entire budget without macro-level rules and constraints.\n\nThe successful outcomes of this domain include strategic alignment, resource efficacy, governed execution via actionable eligibility rules and intervention catalogues, and adaptive strategy to shifting ground realities.\n\nFor authoritative business knowledge, concepts, rules, and events, refer to the modular artifacts within this Knowledge Base.",
    "01-domain-overview.md": "# Domain Overview: Programme Management\n\n## Purpose\nGoverns the macro-level coordination, resourcing, and strategic boundaries of humanitarian assistance.\n\n## Mission\nTo allocate finite resources against systemic vulnerabilities by defining what assistance will be provided, to whom it is available, and under what conditions.\n\n## Scope\nBridges the gap between institutional funding mandates and frontline operations.\n\n## Responsibilities\n- Programme Design & Strategy Formulation\n- Intervention Catalogue Management\n- Eligibility Policy Definition\n- Resource Prioritisation & Allocation\n- Strategic Monitoring & Adaptation",
    "02-boundaries.md": "# Domain Boundaries: Programme Management\n\n## Owns\n- Programme definition.\n- Intervention catalogue.\n- Eligibility policy.\n- Prioritisation.\n- Resource and budget planning.\n- Programme adaptation and monitoring.\n\n## Consumes\n- **From Accountability:** Systemic learning reports, evaluations, community feedback.\n- **From Case Management:** Aggregated rejection rates or rapid uptake.\n- **From Resource & Logistics:** Market feasibility, procurement delays.\n- **From Cross-Organisational Coordination:** Gap analyses avoiding overlap.\n\n## Produces\n- **For Case Management:** Intervention Catalogue, Eligibility Rules, operational budgets.\n- **For Resource & Logistics:** Forecasted demand for material goods.\n- **For Accountability:** Strategic objectives and outcome indicators.\n\n## Explicitly Out of Scope\n- Individual case assessment.\n- Aid delivery.\n- Procurement, warehouse operations, logistics.\n- Impact evaluation.\n- Cross-organisation coordination.",
    "03-concepts.md": "# Business Concepts\n\n- Programme\n- Intervention Catalogue\n- Intervention Offering\n- Objective\n- Outcome Target\n- Target Population\n- Eligibility Rule\n- Priority\n- Allocation\n- Budget\n- Grant\n- Geographic Area\n- Sector\n- Indicator\n- Programme Cycle",
    "04-relationships.md": "# Business Relationships\n\n- A **Programme** targets a **Target Population**.\n- A **Programme** contains an **Intervention Catalogue**.\n- An **Intervention Catalogue** defines multiple **Intervention Offerings**.\n- A **Grant** funds a **Programme**.\n- A **Programme** spans a **Geographic Area**.\n- An **Eligibility Rule** governs an **Intervention Offering**.\n- A **Budget** constrains an **Intervention Offering**.\n- A **Sector** categorizes a **Programme**.\n- An **Indicator** measures a **Programme**'s success.\n- **Priority** influences **Allocation**.",
    "05-business-rules.md": "# Business Rules\n\n## Universal Policies\n- Principles of impartiality, neutrality, and independence in programme design.\n\n## Donor Policies\n- Strict rules governing how specific funds can be used (e.g., restricted vs. unrestricted funding, origin constraints).\n\n## Regional / Government Policies\n- National disaster response frameworks dictating permitted intervention types.\n\n## Organisation Policies\n- Internal strategic mandates (e.g., \"We only do WASH and Health\").\n\n## Programme Policies\n- Specific constraints formulated for a single initiative.\n\n## Constraints\n- **Financial:** Strict budget ceilings and rigid grant cycles.\n- **Regulatory:** Host government restrictions.\n- **Operational:** Market capacity limitations.\n- **Donor:** Earmarked funds.",
    "06-business-events.md": "# Business Events\n\n- **Programme Created:** A new programmatic initiative is drafted.\n- **Funding Secured:** A grant or budget is formally committed.\n- **Programme Approved:** The programme is authorized to commence operations.\n- **Intervention Added / Removed:** The catalogue is updated.\n- **Eligibility Updated:** Rules governing access are modified.\n- **Budget Allocated:** Funds are distributed to specific intervention lines.\n- **Programme Expanded:** Target populations or geographic areas are increased.\n- **Programme Suspended:** Operations are halted due to security or compliance issues.\n- **Programme Revised:** Major strategic shifts in objectives or modalities.\n- **Programme Closed:** The initiative reaches its end date or exhausts funding.",
    "07-business-lifecycles.md": "# Business Lifecycles\n\nThe Programme Cycle represents a macro-level lifecycle:\n1. **Needs Prioritisation & Planning:** Designing objectives, targets, and budgets.\n2. **Approval & Securing Funding:** Grant planning and final authorization.\n3. **Implementation Oversight:** Strategic monitoring and budget tracking.\n4. **Programme Revision/Adaptation:** Adjusting allocations and rules mid-cycle based on reality.\n5. **Programme Closure:** Formally ending operations.\n\n*(This lifecycle governs the Programme itself, distinct from the individual case lifecycles in Case Management).* ",
    "08-decision-points.md": "# Significant Business Decisions\n\n## 1. Programme Initiation Decision\nDetermining if a new programme should be created.\n- **Required Information:** Population assessments, donor calls, strategic objectives.\n- **Responsible Business Role:** Programme Director.\n- **Justification:** Authorize Organisational effort and secure funding based on aggregate need.\n\n## 2. Intervention Inclusion Decision\nDetermining which interventions belong in the catalogue.\n- **Required Information:** Needs assessments, cost-benefit analyses, market feasibility.\n- **Responsible Business Role:** Technical Advisor / Programme Manager.\n- **Justification:** Define the actionable menu available to Case Management.\n\n## 3. Eligibility Rule Definition Decision\nSetting the criteria for receiving an intervention.\n- **Required Information:** Vulnerability criteria, donor mandates.\n- **Responsible Business Role:** Programme Manager.\n- **Justification:** Ensure equitable distribution of finite resources.\n\n## 4. Resource Reallocation Decision\nShifting budgets between interventions or geographic areas.\n- **Required Information:** Burn rates, emergent field reports.\n- **Responsible Business Role:** Budget Owner / Programme Manager.\n- **Justification:** Adapt to unexpected crises or low uptake.",
    "09-information-requirements.md": "# Information Requirements\n\n- **Population Assessments:** Macro-level data on community vulnerabilities.\n- **Funding Availability:** Financial constraints and grant conditions.\n- **Strategic Objectives:** Organisational or national response goals.\n- **Operational Constraints:** Security, market, or logistical limitations on the ground.\n- **Programme Performance:** Burn rates and macro-level output reports.\n- **Humanitarian Indicators:** Standardized metrics justifying intervention.",
    "10-open-questions.md": "# Open Questions\n\n- How are overlapping eligibility rules managed when a single Organisation runs multiple concurrent programmes addressing similar needs?\n- Who explicitly holds the authority to grant a \"Policy Waiver\" when a highly vulnerable individual fails a strict technical eligibility rule?\n- How is the mathematical translation between an overarching \"Grant Budget\" and a per-household \"Intervention Cost\" dynamically maintained when market prices fluctuate?\n- How are multi-sectoral programmes governed when different Sector Leads hold conflicting priorities for the same target population?",
    "11-evidence.md": "# Supporting Evidence\n\n*(Pending Discovery)*\nExplicit evidentiary documents detailing standard programme cycles and donor compliances will be populated as discovered.",
    "12-domain-invariants.md": "# Domain Invariants\n\n- **Macro Rule Setting:** Case Management can never offer an intervention that Programme Management has not defined and budgeted.\n- **Funding Constraints:** Restricted donor funding cannot be fungibly shifted without formal reallocation decisions, regardless of urgent ground need.\n- **Separation of Altitudes:** Programme Management never evaluates the specific vulnerability of an individual household; it evaluates population aggregates.",
    "13-business-language.md": "# Business Language\n\n## Preferred Terms\n- **Programme:** The overarching strategic initiative.\n- **Intervention Catalogue:** The menu of approved interventions.\n- **Eligibility Rule:** The formal criteria for inclusion.\n- **Budget:** Financial constraint.\n- **Grant:** The donor funding mechanism.\n\n## Synonyms\n- **Project:** Often used interchangeably with Programme, though a Programme may technically contain multiple Projects.\n- **Response Plan:** Synonym for a major programme strategy.\n\n## Ambiguous Terminology\n- **Needs Assessment:** Can mean macro-level population assessment (Programme) or micro-level household assessment (Case Management).\n- **Targeting:** Can mean geographic selection (Programme) vs. individual eligibility (Case Management).",
    "STATUS.md": "# Status\n\n`\nOverview: Complete\nBoundaries: Complete\nConcepts: Complete\nRelationships: Complete\nBusiness Rules: Complete\nEvents: Complete\nLifecycles: Complete\nDecision Points: Complete\nInformation Requirements: Complete\nOpen Questions: 4 identified\nEvidence: Pending Discovery\nDomain Invariants: Complete\nBusiness Language: Complete\nClient Validation: Pending\n`"
}

create_files(cm_dir, "Case Management", cm_files)
create_files(pm_dir, "Programme Management", pm_files)

# Remove the old flat files to complete migration
if os.path.exists("docs/02-discovery/CASE_MANAGEMENT_DISCOVERY.md"):
    os.remove("docs/02-discovery/CASE_MANAGEMENT_DISCOVERY.md")
if os.path.exists("docs/02-discovery/PROGRAMME_MANAGEMENT_DISCOVERY.md"):
    os.remove("docs/02-discovery/PROGRAMME_MANAGEMENT_DISCOVERY.md")
